Lesson3
artccche/tasks pull request #4
Opened 2023-05-31 14:04 UTC by artccche

2023-06-18 15:49 UTC, a-kosak-mbx requested changes
Какая-то каша вышла. Разделите файлы на части по заданиям. Здесь вы добавили сразу 4 файла, причем task_1 я уже проверял. И в lesson_3.py допишите в комментариях условия задач. После этого создайте на каждое задание свой реквест.

2023-07-05 14:07 UTC, a-kosak-mbx requested changes
Все задачи выполнены с ошибками. Нужно переделать. И добавьте к каждой задаче ее описание (задание из лекции) в виде комментариев.

2023-07-05 14:07 UTC, a-kosak-mbx commented on tasks/lesson_3.py
> +print(the_longest_word)
А знаки препинания?

2023-07-05 14:07 UTC, a-kosak-mbx commented on tasks/lesson_3.py
> +print(no_replay)
А дубликаты?

2023-07-05 14:07 UTC, a-kosak-mbx commented on tasks/lesson_3.py
> +        elif char.islower():
Зачем проверка на islower, если никаким другим символ быть уже не может?

2023-09-12 17:04 UTC, artccche commented on tasks/lesson_3.py
> +print(the_longest_word)
sentence = input("Введите предложение: ")
words = sentence.split()
longest_word = ""
for word in words:
    word = word.strip(",.!?")
    if len(word) > len(longest_word):
        longest_word = word
print("Самое длинное слово в предложении:", longest_word)

2023-09-12 17:05 UTC, artccche commented on tasks/lesson_3.py
> +print(no_replay)
sentence = input("Введите строку: ")
new_sentence = ""
for char in sentence:
    if char not in new_sentence and char != " ":
        new_sentence += char
print(new_sentence)

2023-09-12 17:06 UTC, artccche commented on tasks/lesson_3.py
> +        elif char.islower():
sentence = input("Введите строку: ")
lower_count = 0
upper_count = 0
for char in sentence:
    if char.isalpha() and char.isascii():
        if char.islower():
            lower_count += 1
        elif char.isupper():
            upper_count += 1
print("Количество строчных букв:", lower_count)
print("Количество прописных букв:", upper_count)

2023-09-12 17:06 UTC, merged